### ISSUE TITLE
MONGODB

### ISSUE THREAD

**Issue by naedmi** [HexxagonHTWG/Hexxagon#40]
"Use MongoDB to build a second DB implementation.
Again, use the DAO Pattern to make the interface independent of the used DB."

[ref](https://docs.google.com/presentation/d/1Hb58fSQKeXJhQuGIsvGOgi-VwjlzJpkPPNFQcaM7rNg/edit#slide=id.g549a4d7304_0_312)

**Comment by Ostabo** [comment]
TODO: make save return 500 on error
